#!/bin/bash
mkdir ~/.config/seraphic/
xml2csv -i https://www.youtube.com/feeds/videos.xml?channel_id=UCBdf0aiFd7n9uRiIX6JBvjQ -m https://raw.githubusercontent.com/prinixos/seraphic/main/mapping -o ~/.config/seraphic.csv
